name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.TOKEN_ACTION }}
    - name: Bump version and push tag
      uses: TriPSs/conventional-changelog-action@v1.3.0
      with:
        github-token: ${{ secrets.TOKEN_ACTION }}
        git-message: 'chore(release): {version}'
        preset: '@favoloso/emoji'
        tag-prefix: ''
        output-file: 'CHANGELOG.md'
